### PR TITLE
Remove mezzanine and add preliminary wagtail integration for content management

### PR DESCRIPTION
**Pull request by rlskoeser**
Work related to #97 #70 

- removes mezzanine
- undoes mezzanine/grappelli harmonization
- basic wagtail installation and homepage model
- preliminary wagtail content page
- preliminary wagtail editorial list and content page models

Not yet handled:
- config wysiwyg editor for collections description
- xml sitemaps (previously powered by mezzanine)
- content editor group permissions for editing wagtail CMS content (maybe not necessary? have to check how wagtail handles permissions)
- check into wagtail 400/500 error page handling for mezzanine equivalent
- fixtures for pa11y-ci test on travis

If you run into migration errors, switch to develop branch and migrate the mezzanine `pages` app to zero, and then switch to feature branch and run migrate.

### CODE REVIEW

**Comment by bwhicks** [comment]
The code looks great, but I'm struggling to get Wagtail to show pages and the hierarch without a fixture.

**Comment by rlskoeser** [comment]
Updates last week since the initial PR was made:
- add a fixture to use for development and pa11y test
- implement xml sitemaps
- get pa11y ci test running and passing (@bwhicks would appreciate your eyes on how I handled the second Solr core in the travis-ci config)
- add unit tests for new page models and views, clean up unused code identified by test coverage
- update 404 and 500 templates after removing mezzanine
- add some minor customization to wagtail backend: PPA logo, CAS login button (without revisiting styles)

**Comment by thatbudakguy** [comment]
This is working great for me using the fixture. I expected to find it in `pages/fixtures` though rather than `common`...is that weird?

**Comment by rlskoeser** [comment]
@thatbudakguy yes, the fixtures would make more sense under `pages`; I noticed that at some point after I'd created them, not sure why I put them there.

**Comment by bwhicks** [comment]
@rlskoeser That looks solid for the core creation. You could add it to the solr configuration script, but I feel like it probably works better as its own step in the travis config to flag it to our attention.

**Pull request merged**
